export default{
    USER_CREATION_SUCCESS: 'User created successfully',
    USER_CREATION_FAILED: 'User creation failed',
    USER_NOT_FOUND: 'User not found',
    USER_NOT_ACTIVE: 'User is not active',
    INVALID_LOGIN: 'Invalid login credentials',
    LOGIN_SUCCESS: 'Login successful',
    INVALID_TOKEN: 'Invalid token',
    USER_ALREADY_EXISTS: 'Auth user already exists',
    USER_UPDATED_SUCCESS: 'User updated successfully',
    USER_UPDATED_FAILED: 'User update failed',
    USER_DELETED_SUCCESS: 'User deleted successfully',
    USER_DELETED_FAILED: 'User deletion failed',
    USER_FETCHED_SUCCESS: 'User fetched successfully',
    USER_FETCHED_FAILED: 'User fetch failed',
    USER_LIST_FETCHED_SUCCESS: 'User list fetched successfully',
    USER_LIST_FETCHED_FAILED: 'User list fetch failed',
    USER_PASSWORD_RESET_SUCCESS: 'User password reset successfully',
    USER_PASSWORD_RESET_FAILED: 'User password reset failed',
}